/*
 * notifier
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddTelegramChannelBody {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "telegram_username")]
    pub telegram_username: String,
}

impl AddTelegramChannelBody {
    pub fn new(user_id: String, telegram_username: String) -> AddTelegramChannelBody {
        AddTelegramChannelBody {
            user_id,
            telegram_username,
        }
    }
}


