/*
 * notifier
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddChannelBody {
    #[serde(rename = "service_username")]
    pub service_username: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "service_id")]
    pub service_id: String,
}

impl AddChannelBody {
    pub fn new(service_username: String, user_id: String, service_id: String) -> AddChannelBody {
        AddChannelBody {
            service_username,
            user_id,
            service_id,
        }
    }
}


