/*
 * notifier
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChannelsResponse {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "channels")]
    pub channels: Vec<crate::models::ChannelResponse>,
}

impl ChannelsResponse {
    pub fn new(user_id: String, channels: Vec<crate::models::ChannelResponse>) -> ChannelsResponse {
        ChannelsResponse {
            user_id,
            channels,
        }
    }
}


