/*
 * notifier
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChannelResponse {
    #[serde(rename = "service_id")]
    pub service_id: String,
    #[serde(rename = "service_username")]
    pub service_username: String,
}

impl ChannelResponse {
    pub fn new(service_id: String, service_username: String) -> ChannelResponse {
        ChannelResponse {
            service_id,
            service_username,
        }
    }
}


