/*
 * notifier
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTelegramChatIdBody {
    #[serde(rename = "telegram_username")]
    pub telegram_username: String,
}

impl GetTelegramChatIdBody {
    pub fn new(telegram_username: String) -> GetTelegramChatIdBody {
        GetTelegramChatIdBody {
            telegram_username,
        }
    }
}


